# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'StJhonsAmbulance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ENTALDO

	pod "Alamofire"
  pod 'SCLAlertView'
  pod 'SDWebImage'
  pod 'ACFloatingTextfield-Swift'
  pod 'IQKeyboardManagerSwift'
  pod 'SideMenu'
  pod 'Parchment', '~> 3.2'
  pod 'GoogleMaps'
  pod 'FSCalendar'
  pod 'Starscream'
  pod 'SwiftSignalRClient'
#  pod 'KVKCalendar'
  
  target 'StJhonsAmbulanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StJhonsAmbulanceUITests' do
    # Pods for testing
  end

end
