# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'StJhonsAmbulance' do
  # Comment the next line if you don't want to use dynamic frameworks
 # use_frameworks!

  # Pods for ENTALDO

	pod "Alamofire"
  pod 'SCLAlertView'
  pod 'SDWebImage'
  pod 'ACFloatingTextfield-Swift'
  pod 'IQKeyboardManagerSwift'
  pod 'SideMenu'
  pod 'Parchment', '~> 3.2'
  pod 'GoogleMaps'
  pod 'FSCalendar'
  pod 'SwiftSignalRClient'
#  pod 'KVKCalendar'
  
  target 'StJhonsAmbulanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StJhonsAmbulanceUITests' do
    # Pods for testing
  end

end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
